markdown: kramdown

repository: CV/EduardSergeev


cv:
  name: Eduard Sergeev
  title: Software Developer
  location: Sydney, Australia
  email: eduard.sergeev@gmail.com
  phone: "+61406718185"
  github: https://github.com/EduardSergeev
  stackoverflow: https://stackoverflow.com/users/394253/edka
  linkedin: https://www.linkedin.com/in/eduardsergeev

