name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: gh-pages
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - name: Publish site to a '${{ env.BRANCH }}' branch
      run: |
        VERSION=$(node -p "require('./package.json').version")
        git fetch origin $BRANCH
        git checkout $BRANCH
        rm -fr docs
        mv dist docs
        git add docs
        git -c "user.name=$GIT_AUTHOR_NAME" -c "user.email=$GIT_AUTHOR_EMAIL" commit -m "Build $VERSION"    
      env:
        GIT_AUTHOR_NAME: Auto Publisher
        GIT_AUTHOR_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}

    - name: Push changes
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH }}
