name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: gh-pages
      TZ: Australia/Sydney
    steps:
    - uses: actions/checkout@v2
    - name: Set project version
      id: set-version
      uses: EduardSergeev/project-version-action@v1
    - name: Build '${{ steps.set-version.outputs.project-version }}'
      run: |
        npm install
        npm run build
    - name: Publish site to a '${{ env.BRANCH }}' branch
      run: |
        git reset --hard
        git fetch origin $BRANCH
        git checkout $BRANCH
        rm -fr docs
        mv dist docs
        git add docs
        git -c "user.name=$GIT_AUTHOR_NAME" -c "user.email=$GIT_AUTHOR_EMAIL" commit --allow-empty -m "Build $VERSION"    
      env:
        GIT_AUTHOR_NAME: Auto Publisher
        GIT_AUTHOR_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}

    - name: Push changes
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH }}
